version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/digitallibrary-0.0.1-SNAPSHOT.jar
